import {universes, universeById, buildUniverse, filterUniverse, entityAttributes, analytics, timeline, encodeEdge, validateSavedView} from './universe-model.js';
const $=id=>document.getElementById(id), esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search), id=universeById.has(params.get('universe'))?params.get('universe'):'conditions', graph=buildUniverse(id), config=graph.universe;
const url=(uid,entity)=>`universe.html?universe=${encodeURIComponent(uid)}${entity?'&entity='+encodeURIComponent(entity):''}`;
let scene, selected=graph.nodes.some(n=>n.id===params.get('entity'))?params.get('entity'):graph.primaryNodeIds[0], selectedEdge=graph.edges[0]?.id, filtered=graph, bytePage=0, byteIndex=0, payload;
let session={user:null,permissions:{},bootstrapRequired:false}, serverAvailable=false, views=[], users=[], storageError='';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let state={paused:reduced,flowPaused:reduced,flowDirection:1,dragMode:false,layers:4,layerIds:['shell','structure','core','detail']};
const storageKey=`aster-universe-views-v1:${id}`, filterKey=`aster-universe-filters-v1:${id}`;
document.title=`${config.label} universe · Aster Atlas`;document.documentElement.style.setProperty('--accent',config.accent);
$('universe-title').textContent=config.label+' universe';$('universe-description').textContent=config.description;
$('universe-nav').innerHTML=universes.map(u=>`<a href="${url(u.id)}" ${u.id===id?'aria-current="page"':''}>${esc(u.label)}</a>`).join('');
$('headline-counts').innerHTML=[[graph.primaryNodeIds.length,'PRIMARY ENTITIES'],[graph.nodes.length,'CONNECTED OBJECTS'],[graph.sources.length,'SOURCES']].map(([n,label])=>`<div><b>${n.toString().padStart(2,'0')}</b><span>${label}</span></div>`).join('');
const option=(value,label=value)=>`<option value="${esc(value)}">${esc(label)}</option>`;
$('type').insertAdjacentHTML('beforeend',[...new Set(graph.nodes.map(n=>n.type))].map(v=>option(v)).join(''));
$('source').insertAdjacentHTML('beforeend',graph.sources.map(s=>option(s.id,s.title)).join(''));
$('strength').insertAdjacentHTML('beforeend',[...new Set(graph.edges.map(e=>e.strength))].map(v=>option(v)).join(''));
$('edge-select').innerHTML=graph.edges.map(e=>option(e.id,`${graph.nodes.find(n=>n.id===e.from).short} → ${graph.nodes.find(n=>n.id===e.to).short} · ${e.relation}`)).join('');
$('access-universe').innerHTML=universes.map(u=>option(u.id,u.label)).join('');$('access-universe').value=id;
const filters=()=>({query:$('search').value,type:$('type').value,source:$('source').value,strength:$('strength').value});
const attr=(k,v)=>`<div class="attribute"><span>${esc(k)}</span><b>${esc(v)}</b></div>`;
function sourceLinks(ids){return [...new Set(ids)].map(sid=>graph.sources.find(s=>s.id===sid)).filter(Boolean).map(s=>`<a target="_blank" rel="noopener noreferrer" href="${esc(s.url)}">${esc(s.publisher)} · ${esc(s.title)} ↗</a>`).join('');}
function renderInspector(){const node=graph.nodes.find(n=>n.id===selected);if(!node){$('inspector').innerHTML='<p>Select an entity in this universe.</p>';return;}
 const a=entityAttributes(node,graph), links=graph.edges.filter(e=>e.from===node.id||e.to===node.id);
 $('inspector').innerHTML=`<h3>${esc(node.label)}</h3><p>${esc(node.summary)}</p>${attr('Shared identity',node.id)}${attr('Entity type',node.type)}${attr('Role here',a.primary?'Primary entity':'Connected context')}${attr('Sources',a.sourceCount)}${attr('Relationships',a.connectionCount)}<button data-focus="${esc(node.id)}">Focus this object ↗</button><details open><summary>Evidence quality · ${esc(a.assessment.status)}</summary><div class="risk-note">${a.assessment.reasons.map(r=>`<p>${esc(r.message)}</p>`).join('')}<p>Clinical risk: unassessed.</p></div></details><h4>Relationships</h4>${links.map(e=>`<button data-edge="${esc(e.id)}">${esc(e.relation)} · ${esc(graph.nodes.find(n=>n.id===(e.from===node.id?e.to:e.from)).short)}</button>`).join('')}<details><summary>Object attributes & position</summary><div id="object-position"></div>${attr('Evidence',a.evidenceStrengths.join(', '))}<p>${esc(node.detail||'')}</p></details><h4>Original sources</h4>${sourceLinks(a.sourceIds)}<div class="portals"><h4>Same object, other universes</h4>${universes.filter(u=>u.id!==id&&buildUniverse(u.id).nodes.some(n=>n.id===node.id)).map(u=>`<a href="${url(u.id,node.id)}">${esc(u.label)} universe ↗</a>`).join('')||'<p>No other universe contains this object.</p>'}</div>`;
 $('inspector').querySelectorAll('[data-edge]').forEach(b=>b.onclick=()=>chooseEdge(b.dataset.edge,true));
 $('inspector').querySelector('[data-focus]').onclick=()=>scene?.focusNode?.(node.id);renderPosition();objectControls();
}
function renderPosition(){const node=graph.nodes.find(n=>n.id===selected), position=scene?.getView().positions?.[selected];if($('object-position'))$('object-position').textContent=position?`Scene position: ${position.map(n=>n.toFixed(2)).join(' / ')}`:`Source layout: ${[node.x,node.y,node.z].join(' / ')}`;}
function chooseNode(nodeId){selected=nodeId;scene?.setState({selected});if(scene?.getView().isolatedNodeId)scene.setIsolation(selected);renderInspector();renderList();objectControls();}
function renderList(){const focused=document.activeElement?.dataset?.node;const visible=new Set(filtered.nodes.map(n=>n.id));$('result-count').textContent=`${visible.size} / ${graph.nodes.length}`;$('entity-list').innerHTML=graph.nodes.filter(n=>visible.has(n.id)).map(n=>`<button class="entity-button" aria-pressed="${selected===n.id}" data-node="${esc(n.id)}"><span>${esc(n.short)}</span><small>${esc(n.type)}</small></button>`).join('')||'<p class="empty">No entities match. Clear filters to restore the universe.</p>';$('entity-list').querySelectorAll('button').forEach(b=>b.onclick=()=>chooseNode(b.dataset.node));if(focused)$('entity-list').querySelector(`[data-node="${CSS.escape(focused)}"]`)?.focus({preventScroll:true});}
function applyFilters(persist=true){filtered=filterUniverse(graph,filters());scene?.setState({visibleIds:filtered.visibleIds,visibleEdgeIds:filtered.edges.map(e=>e.id),selected,layerIds:state.layerIds});renderList();const a=analytics(filtered);$('analytics').innerHTML=attr('Matching objects',a.visibleNodes)+attr('Matching relationships',a.visibleEdges)+attr('Primary / context',`${a.primaryNodes} / ${a.contextNodes}`)+attr('Cited sources',a.sourceCount)+attr('Inferred relationships',a.inferredEdges)+attr('Connected components',a.connectedComponents)+Object.entries(a.byType).map(([k,v])=>attr(k,v)).join('')+'<p>Counts reflect search and filter results. Object isolation changes the 3D view only.</p>';if(persist)try{sessionStorage.setItem(filterKey,JSON.stringify(filters()));}catch{}updateStats();}
function restoreFilters(value){for(const [key,dom] of Object.entries({query:'search',type:'type',source:'source',strength:'strength'}))$(dom).value=value?.[key]??(key==='query'?'':'all');}
try{const f=JSON.parse(sessionStorage.getItem(filterKey)||'null');if(f&&validateSavedView({version:1,universeId:id,filters:f}).valid)restoreFilters(f);}catch{}
for(const name of ['search','type','source','strength'])$(name).addEventListener(name==='search'?'input':'change',()=>applyFilters());
$('clear-filters').onclick=()=>{restoreFilters({});applyFilters();};
$('timeline').innerHTML=timeline(graph).map(e=>`<div class="timeline-event"><time>${esc(e.date||'Update date unavailable')}</time>${e.url?`<a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.label)} ↗</a>`:esc(e.label)}<small>${esc(e.detail)}</small></div>`).join('');
function objectControls(){const v=scene?.getView()||{};const node=graph.nodes.find(n=>n.id===selected);$('studio-selection').textContent=node?.label||'Select an object';const manual=v.objectExplosions?.[selected];$('object-explode').value=manual===undefined?0:Math.round(manual*100);$('object-explode-value').textContent=manual===undefined?'Automatic':`${Math.round(manual*100)}% · held`;const isolated=!!v.isolatedNodeId;$('isolate-object').setAttribute('aria-pressed',String(isolated));$('isolate-object').textContent=isolated?'Show connected objects':'Isolate object';}
$('object-explode').oninput=()=>{scene?.setObjectExplosion(selected,Number($('object-explode').value)/100);objectControls();};
$('reassemble-object').onclick=()=>{scene?.setObjectExplosion(selected,0);objectControls();};
$('hover-layers').onclick=()=>{scene?.setObjectExplosion(selected,null);objectControls();};
$('isolate-object').onclick=()=>{scene?.setIsolation(scene?.getView().isolatedNodeId?null:selected);objectControls();updateStats();};
$('render-quality').onchange=()=>{scene?.setQuality($('render-quality').value==='high');updateStats();};
function controls(){objectControls();for(const [dom,key,on,off] of [['drag-mode','dragMode','Orbit mode','Move objects'],['pause-motion','paused','Resume animation','Pause animation'],['pause-flow','flowPaused','Resume all flows','Pause all flows']]){$(dom).textContent=state[key]?on:off;$(dom).setAttribute('aria-pressed',String(state[key]));}$('reverse-flow').textContent=state.flowDirection===1?'Reverse all flows':'Forward all flows';$('pipeline-layers').value=state.layers;$('object-layers').querySelectorAll('input').forEach(i=>i.checked=state.layerIds.includes(i.value));}
$('drag-mode').onclick=()=>{state.dragMode=!state.dragMode;scene?.setDragMode(state.dragMode);controls();};
$('pause-motion').onclick=()=>{state.paused=!state.paused;scene?.setPaused(state.paused);controls();edgeControls();updateStats();};
$('pause-flow').onclick=()=>{state.flowPaused=!state.flowPaused;scene?.setFlowPaused(state.flowPaused);controls();edgeControls();updateStats();};
$('reverse-flow').onclick=()=>{state.flowDirection*=-1;scene?.setFlowDirection(state.flowDirection);controls();edgeControls();updateStats();};
$('reset-scene').onclick=()=>{scene?.reset();renderPosition();};
$('object-layers').onchange=()=>{state.layerIds=[...$('object-layers').querySelectorAll('input:checked')].map(i=>i.value);scene?.setState({layerIds:state.layerIds});};
$('pipeline-layers').onchange=()=>{state.layers=Number($('pipeline-layers').value);scene?.setLayers(state.layers);updateStats();};
function chooseEdge(edgeId,scroll=false,layer){const edge=graph.edges.find(e=>e.id===edgeId);if(!edge)return;selectedEdge=edgeId;$('edge-select').value=edgeId;payload=encodeEdge(edge);bytePage=0;byteIndex=0;$('byte-index').max=payload.bytes.length-1;$('payload-json').textContent=JSON.stringify(payload.payload,null,2);$('payload-summary').innerHTML=attr('Evidence strength',edge.strength)+attr('Relationship',edge.relation)+attr('Record length',`${payload.bytes.length} bytes`)+(layer!==undefined?attr('Selected pipeline layer',['Identity','Relationship','Provenance','Record'][layer]):'')+`<p>${esc(edge.note||'')}</p>`+sourceLinks(edge.sourceIds)+`<div class="edge-controls"><button id="edge-pause">Pause this relationship</button><button id="edge-reverse">Reverse this relationship</button><span id="edge-flow-status"></span></div>`;
 $('edge-pause').onclick=()=>{const flow=scene?.getEdgeFlows?.()[selectedEdge]||{paused:false,direction:1};scene?.setEdgeFlow?.(selectedEdge,{...flow,paused:!flow.paused});edgeControls();};$('edge-reverse').onclick=()=>{const flow=scene?.getEdgeFlows?.()[selectedEdge]||{paused:false,direction:1};scene?.setEdgeFlow?.(selectedEdge,{...flow,direction:-flow.direction});edgeControls();};edgeControls();renderBytes();if(scroll)$('payload-section').scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'});}
function edgeControls(){const flow=scene?.getEdgeFlows?.()[selectedEdge]||{paused:false,direction:1};if($('edge-pause')){$('edge-pause').textContent=flow.paused?'Resume this relationship':'Pause this relationship';$('edge-pause').disabled=!scene?.setEdgeFlow;$('edge-reverse').disabled=!scene?.setEdgeFlow;$('edge-flow-status').textContent=`${state.paused||state.flowPaused?'Globally paused':flow.paused?'Stopped':'Circulating'} · ${flow.direction===1?'forward':'reverse'} direction`;}}
function renderBytes(){if(!payload)return;const focused=document.activeElement?.dataset?.byte;const start=bytePage*32,end=Math.min(start+32,payload.bytes.length);$('byte-grid').innerHTML=Array.from(payload.bytes.slice(start,end),(b,i)=>`<button aria-pressed="${start+i===byteIndex}" data-byte="${start+i}" aria-label="Byte ${start+i}, hex ${b.toString(16).padStart(2,'0')}"><small>${start+i}</small>${b.toString(16).padStart(2,'0').toUpperCase()}</button>`).join('');$('byte-grid').querySelectorAll('button').forEach(b=>b.onclick=()=>{byteIndex=Number(b.dataset.byte);renderBytes();});$('byte-page').textContent=`${start}–${end-1} / ${payload.bytes.length} bytes`;$('bytes-prev').disabled=bytePage===0;$('bytes-next').disabled=end===payload.bytes.length;$('byte-index').value=byteIndex;const b=payload.bytes[byteIndex];$('bit-detail').textContent=`Offset ${byteIndex} · decimal ${b} · hex 0x${b.toString(16).padStart(2,'0').toUpperCase()}\nBits (most significant first): ${payload.bits[byteIndex].split('').join(' ')}`;if(focused!==undefined)$('byte-grid').querySelector(`[data-byte="${focused}"]`)?.focus({preventScroll:true});}
$('edge-select').onchange=()=>chooseEdge($('edge-select').value);$('bytes-prev').onclick=()=>{bytePage--;renderBytes();};$('bytes-next').onclick=()=>{bytePage++;renderBytes();};$('byte-index').oninput=()=>{byteIndex=Math.max(0,Math.min(payload.bytes.length-1,Math.floor(Number($('byte-index').value)||0)));bytePage=Math.floor(byteIndex/32);renderBytes();};
async function api(path,body,method='POST'){const response=await fetch(path,{method:body===undefined?'GET':method,credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':session.user?.csrf||''},...(body===undefined?{}:{body:JSON.stringify(body)})});let value;try{value=await response.json();}catch{throw Error('Workspace service is unavailable.');}if(!response.ok)throw Error(value.error||'Workspace request failed.');return value;}
function localViews(){try{const value=JSON.parse(localStorage.getItem(storageKey)||'[]');if(!Array.isArray(value)||value.length>100)throw Error();const valid=value.filter(v=>typeof v.id==='string'&&typeof v.name==='string'&&validateSavedView(v.view).valid&&v.view.universeId===id);storageError=valid.length!==value.length?'Some invalid saved views were ignored.':'';return valid;}catch{storageError='Browser storage is unavailable or contains invalid views.';return [];}}
function currentView(){const v=scene?.getView()||{};const value={version:1,universeId:id,name:$('view-name').value.trim(),selectedNodeId:selected,selectedEdgeId:selectedEdge,filters:filters(),...state,...(v.camera?{camera:{position:v.camera.position,target:v.camera.target},positions:v.positions,edgeFlows:scene.getEdgeFlows(),objectExplosions:v.objectExplosions||{},isolatedNodeId:v.isolatedNodeId??null}:{})};const checked=validateSavedView(value);if(!checked.valid)throw Error(checked.errors.join(' '));return checked.value;}
async function loadViews(){const role=session.permissions[id]||'none', signed=!!session.user;const canSave=!signed||['owner','editor'].includes(role);$('save-form').querySelector('button').disabled=!canSave;$('view-mode').textContent=signed?`${session.user.username} · ${role} access. Personal views stored by the local workspace service.`:'Guest views stay in this browser. They are not private account storage.';try{views=signed?(await api(`/api/universes/${id}/views`)).views:localViews();$('save-status').textContent=storageError;renderViews();if(signed){const result=await api(`/api/universes/${id}/events`);$('activity').innerHTML=result.events.map(e=>`<p>${esc(new Date(e.created*1000).toLocaleString())} · ${esc(e.action)}</p>`).join('')||'<p>No saved-view activity.</p>';}else $('activity').innerHTML='<p>Sign in for account activity history.</p>';}catch(error){views=[];renderViews();$('save-status').textContent=error.message;$('activity').textContent='Workspace activity unavailable.';}}
function renderViews(){$('saved-views').innerHTML=views.map(v=>`<div class="saved-view"><button data-load="${esc(v.id)}">${esc(v.name)}</button><button data-delete="${esc(v.id)}" aria-label="Delete ${esc(v.name)}" ${session.user&&!['owner','editor'].includes(session.permissions[id])?'disabled':''}>×</button></div>`).join('')||'<p>No saved views in this universe.</p>';$('saved-views').querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const entry=views.find(v=>v.id===b.dataset.load), checked=validateSavedView(entry?.view);if(!checked.valid){$('save-status').textContent='This saved view is invalid.';return;}const v=checked.value;restoreFilters(v.filters);state={...state,...Object.fromEntries(Object.keys(state).filter(k=>v[k]!==undefined).map(k=>[k,v[k]]))};selected=v.selectedNodeId||graph.primaryNodeIds[0];scene?.setView({...v,selected});controls();applyFilters();renderInspector();if(v.selectedEdgeId)chooseEdge(v.selectedEdgeId);$('save-status').textContent=`Loaded “${entry.name}”.`;});$('saved-views').querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{try{if(session.user)await api(`/api/universes/${id}/views/${encodeURIComponent(b.dataset.delete)}`,{},'DELETE');else{const existing=localViews();localStorage.setItem(storageKey,JSON.stringify(existing.filter(v=>v.id!==b.dataset.delete)));}await loadViews();}catch(e){$('save-status').textContent=e.message;}});}
$('save-form').onsubmit=async e=>{e.preventDefault();try{const view=currentView(),name=view.name;if(!name)throw Error('Enter a view name.');if(session.user)await api(`/api/universes/${id}/views`,{name,view});else{const existing=localViews();if(storageError)throw Error(storageError);if(existing.length>=100)throw Error('Limit of 100 views reached.');existing.unshift({id:crypto.randomUUID(),name,view,created:Date.now()/1000});localStorage.setItem(storageKey,JSON.stringify(existing));}await loadViews();$('save-status').textContent=`Saved “${name}”.`;}catch(error){$('save-status').textContent=error.message;}};
async function refreshSession(){try{session=await api('/api/session');serverAvailable=true;}catch{session={user:null,permissions:{},bootstrapRequired:false};serverAvailable=false;}await accountUI();await loadViews();}
async function accountUI(){const signed=!!session.user;$('account-status').textContent=!serverAvailable?'Local workspace service is unavailable. Browser views remain available.':signed?`Signed in as ${session.user.username}. ${session.user.isOwner?'Workspace owner.':''}`:session.bootstrapRequired?'Create the first local owner account to enable protected workspace storage.':'Sign in to your local workspace.';$('login-form').hidden=signed||!serverAvailable;$('login-submit').textContent=session.bootstrapRequired?'Create owner account':'Sign in';$('logout').hidden=!signed;$('owner-panel').hidden=!session.user?.isOwner;if(session.user?.isOwner){users=(await api('/api/users')).users;$('account-list').innerHTML=users.filter(u=>!u.owner).map(u=>option(u.id,u.username)).join('');$('grant-access').querySelector('button').disabled=!users.some(u=>!u.owner);$('access-summary').textContent=users.map(u=>`${u.username}: ${u.owner?'owner · all universes':universes.map(v=>`${v.label} ${u.permissions[v.id]||'none'}`).join(' / ')}`).join('\n');}}
$('access-open').onclick=()=>{$('access-dialog').showModal();scene?.setVisibilityOverride(null);};$('access-close').onclick=()=>$('access-dialog').close();
$('login-form').onsubmit=async e=>{e.preventDefault();try{await api(session.bootstrapRequired?'/api/bootstrap':'/api/login',{username:$('username').value,password:$('password').value});$('password').value='';await refreshSession();}catch(error){$('account-status').textContent=error.message;}};
$('logout').onclick=async()=>{try{await api('/api/logout',{});await refreshSession();}catch(e){$('account-status').textContent=e.message;}};
$('create-user').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await api('/api/users',{username:f.get('username'),password:f.get('password')});e.target.reset();await accountUI();$('account-status').textContent='Account created. Assign its universe permissions below.';}catch(error){$('account-status').textContent=error.message;}};
$('grant-access').onsubmit=async e=>{e.preventDefault();try{await api('/api/access',{userId:$('account-list').value,universe:$('access-universe').value,role:$('access-role').value});await accountUI();$('account-status').textContent='Universe permission updated.';}catch(error){$('account-status').textContent=error.message;}};
function updateStats(){if(!scene)return;const s=scene.getStats();$('scene-status').textContent=`${s.visibleNodeCount} objects / ${s.visibleEdgeCount} relationships · ${s.layerCount} pipeline layers`;if($('render-stats'))$('render-stats').textContent=JSON.stringify(s,null,2);}
$('universe-stage').insertAdjacentHTML('afterend','<details class="render-details"><summary>Rendering diagnostics</summary><button id="refresh-stats">Refresh measurements</button><pre id="render-stats"></pre></details>');$('refresh-stats').onclick=updateStats;
renderInspector();applyFilters(false);controls();chooseEdge(selectedEdge);await refreshSession();
try{const {createUniverseScene}=await import('./universe-scene.js');scene=createUniverseScene({canvas:$('universe-canvas'),container:$('universe-stage'),labels:$('universe-labels'),nodes:graph.nodes,edges:graph.edges,reducedMotion:reduced,onSelect:chooseNode,onEdge:(edgeId,{layer}={})=>chooseEdge(edgeId,true,layer),onMove:()=>{renderPosition();updateStats();},onReady:()=>updateStats()});scene.setLayers(state.layers);scene.setPaused(state.paused);scene.setFlowPaused(state.flowPaused);scene.setQuality($('render-quality').value==='high');applyFilters(false);edgeControls();renderPosition();objectControls();}catch(error){$('scene-status').textContent='3D unavailable · use the entity list and relationship inspector.';console.error('Universe renderer unavailable:',error);for(const control of ['drag-mode','pause-motion','pause-flow','reverse-flow','reset-scene','pipeline-layers','isolate-object','object-explode','reassemble-object','hover-layers','render-quality'])$(control).disabled=true;}
window.addEventListener('pagehide',()=>scene?.dispose());
