import { evidencePackage as graph } from './win-evidence.js';
import { validateGraph,createCanonicalResolver,gateExplanation,assessCandidate,noSupportedRoute,REVIEW_CONFIG } from './win-review.js';
import { extractionArtifact } from './win-openai.js';
const esc=value=>String(value??'unknown').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
const nodes=new Map(graph.nodes.map(n=>[n.id,n])),edges=new Map(graph.edges.map(e=>[e.id,e])),sources=new Map(graph.sources.map(s=>[s.id,s]));
const resolver=createCanonicalResolver(graph.nodes);
const opportunity=graph.candidateOpportunity;
const focalId=graph.nodes.find(n=>n.type==='disease'&&/Friedreich/i.test(n.canonicalName))?.id;
const edgeIds=key=>opportunity[key]||[];
const stepMeta=Object.freeze({connection:['1','Connection'],assets:['2','Existing work'],action:['3','This week'],uncertainty:['4','Uncertainty'],impact:['5','Milestone']});
const citations=ids=>ids.filter(id=>edges.has(id)).map(id=>`<button class="win-cite" data-evidence="${esc(id)}">Evidence · ${esc(id)}</button>`).join('');
function claims(ids){return ids.map(id=>{const edge=edges.get(id);if(!edge)return '';const gate=gateExplanation(graph,[{text:edge.claim,edgeIds:[id]}],{allowPendingExpert:true});return edge.evidenceStatus==='contradictory'?`<p class="win-note"><b>Counterevidence:</b> ${esc(edge.claim)}</p>${citations([id])}`:gate.visible?`<p>${esc(edge.claim)}</p><small>${esc(gate.sentences[0]?.label||'Pending expert review')} · ${esc(edge.evidenceStatus)}</small><br>${citations([id])}`:`<p class="win-note">Claim withheld: supporting evidence or approval is missing.</p>`;}).join('');}
const pairs=object=>Object.entries(object).filter(([,v])=>typeof v==='string').map(([key,value])=>`<dt>${esc(key.charAt(0).toUpperCase()+key.slice(1))}</dt><dd>${esc(value)}</dd>`).join('');
export function coordinationImpact(before,after){
 if(!Number.isFinite(before)||!Number.isFinite(after)||before<=0||after<=0||!Number.isFinite(before/after))return null;
 return {ratio:before/after,label:`${(before/after).toFixed(1)}× estimated coordination ratio`};
}
export const coordinationHypothesis=Object.freeze({
 baselineWeeks:10,assistedWeeks:1,ratio:coordinationImpact(10,1).ratio,
 milestone:'Reach an expert-ready, source-linked model-selection review brief.',
 label:'Illustrative coordination hypothesis — not a measured result',
 assumptions:'The focal question exists, public records remain current, and source owners respond.',
 exclusions:'Expert response time, ethics review, experiments, biological progress, and clinical review are excluded and are not accelerated.'
});
export function initWinJourney(){
 const validation=validateGraph(graph);let active='connection',returnFocus=null;
 const inspector=$('win-inspector');
 function dialog(title,body){returnFocus=document.activeElement;$('win-inspector-title').textContent=title;$('win-inspector-body').innerHTML=body;inspector.showModal();}
 function sourceMarkup(source){if(!source)return '<p>Source record unavailable; claim withheld from action.</p>';return `<p><b>${esc(source.title)}</b><br>${esc(source.publisher||'Publisher recorded in original')} · Published: ${esc(source.published&&source.published!=='unknown'?source.published:source.publicationYear?`${source.publicationYear} (exact date unknown)`:'unknown')} · Updated: ${esc(source.updated||'unknown')} · Checked: ${esc(source.lastChecked||graph.checkedAt||'unknown')}</p><a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">Open original source ↗</a>`;}
 function evidence(ids){return ids.map(id=>{const e=edges.get(id);if(!e)return '';return `<article><h3>${esc(e.claim)}</h3><p class="review-label">${esc(e.evidenceStatus)} · ${esc(e.strength)} · ${esc(e.reviewStatus)} · Checked ${esc(e.lastChecked)}</p><p><b>Limitations:</b> ${esc(e.limitations)}</p>${e.support.map(s=>`<section>${s.passage?`<blockquote>${esc(s.passage)}</blockquote>`:`<p><b>Structured source field:</b> ${esc(s.field)}</p>`}${sourceMarkup(sources.get(s.sourceId))}</section>`).join('')}<small>Stable claim: ${esc(e.id)} · ${esc(e.from)} → ${esc(e.to)}</small></article>`;}).join('');}
 function showEvidence(ids){const paired=new Set([...ids,...edgeIds('limitationEdgeIds')]);dialog('Evidence and limits',evidence([...paired]));}
 function updateSummary(){const connection=edges.get(edgeIds('mechanismEdgeIds')[0]);const limit=edges.get(edgeIds('limitationEdgeIds')[0]);const a=opportunity.action||{};$('summary-connection').textContent=connection?.claim||opportunity.title;$('summary-limit').textContent=limit?.claim||'Model and tissue differences require review.';$('summary-action').textContent=a.what||a.text||'Request a model-fit review from the resource owner and a mechanism specialist.';}
 function action(){const a=opportunity.action||{};$('journey-action').innerHTML=`<span class="win-kicker">MARIA’S NEXT STEP / THIS WEEK</span><h2>Request a model-fit review.</h2><p>${esc(a.what||a.text||'Ask the resource owner and a mechanism specialist to review scientific fit before reuse.')}</p><p><b>Partner:</b> ${esc(a.who||'Named resource owner and qualified disease specialist')}</p><p><b>Output:</b> ${esc(a.output||'A written fit assessment and missing-evidence list.')}</p><details><summary>Question, decision and limits</summary><dl>${pairs(Object.fromEntries(Object.entries(a).filter(([k])=>!['what','text','who','output'].includes(k))))}</dl></details><button class="win-cite" data-action-evidence>Evidence for this action</button><p class="win-note">Research coordination proposal. Expert review is pending; asset reuse has not been validated.</p>`;}
 function render(){
  const panel=$('win-panel');document.querySelectorAll('[data-win-step]').forEach(b=>{b.setAttribute('aria-current',b.dataset.winStep===active?'step':'false');});
  if(active==='connection')panel.innerHTML=`<span class="win-kicker">SOURCE-LINKED CONNECTION / REVIEW REQUIRED</span><h2>${esc(opportunity.title)}</h2>${claims(edgeIds('mechanismEdgeIds'))}<details><summary>Variant and informative phenotypes</summary>${claims(graph.edges.filter(e=>['variant','phenotype'].includes(nodes.get(e.to)?.type)).map(e=>e.id))}</details>`;
  if(active==='assets')panel.innerHTML=`<span class="win-kicker">EXISTING WORK / CONFIRM REUSE TERMS</span><h2>Start from an existing research asset.</h2>${claims(edgeIds('assetEdgeIds'))}<details><summary>Study and investigator context</summary>${claims(graph.edges.filter(e=>['study','investigator'].includes(nodes.get(e.to)?.type)).map(e=>e.id))}</details>${claims(edgeIds('limitationEdgeIds').slice(0,1))}`;
  if(active==='action')panel.innerHTML=`<span class="win-kicker">ACTION / A DECISION, NOT A TREATMENT</span><h2>Define the experiment before requesting a model.</h2><dl>${pairs(opportunity.action||{})}</dl>${citations([...edgeIds('assetEdgeIds'),...edgeIds('partnerEdgeIds')])}`;
  if(active==='uncertainty'){
   const ranked=assessCandidate({edgeIds:opportunity.edgeIds||[...edgeIds('mechanismEdgeIds'),...edgeIds('assetEdgeIds')],dimensions:opportunity.dimensions||{evidenceStrength:1,mechanisticRelevance:.75,assetUsefulness:.5,actionability:.5},apiStatus:'not-called'},graph);
   panel.innerHTML=`<span class="win-kicker">COUNTEREVIDENCE / KEEP DIFFERENCES VISIBLE</span><h2>A shared pathway does not prove a reusable model.</h2>${claims(edgeIds('limitationEdgeIds'))}<p><b>Rejected candidate:</b> FRDA → A-T based only on ataxia. That broad symptom does not establish the mechanism or asset fit needed here.</p>${citations(graph.rejectedCandidates.flatMap(c=>c.edgeIds))}<details><summary>Review dimensions and missing evidence</summary><p>Disposition: ${esc(ranked.decision)}. ${esc(ranked.reasons.join(' '))}</p><p>No confidence score is invented while independent assessment is pending.</p><dl>${pairs(opportunity.dimensionRationales||{})}</dl><dl>${pairs(Object.fromEntries(Object.entries(ranked.dimensions).map(([k,v])=>[k,Number.isFinite(v)?`${v} / 1 · threshold ${REVIEW_CONFIG.dimensions[k]}`:'Not scored · independent review pending'])))}</dl><p>Missing: an expert-approved cross-disease protocol, model availability confirmation, and reuse terms. These could change the proposal.</p></details>`;
  }
  if(active==='impact'){
   const impact=coordinationHypothesis;
   panel.innerHTML=`<span class="win-kicker">MILESTONE / MODEL-SELECTION REVIEW BRIEF</span><h2>${esc(impact.ratio)}× coordination hypothesis.</h2><output id="win-ratio" aria-label="Illustrative ten times coordination hypothesis">${esc(impact.ratio)}×</output><p>Hypothesis: reduce the path to a sourced contact-and-review decision from ${esc(impact.baselineWeeks)} fragmented weeks to ${esc(impact.assistedWeeks)} atlas-assisted week.</p><table><thead><tr><th>Milestone</th><th>Baseline</th><th>With atlas</th></tr></thead><tbody><tr><td>${esc(impact.milestone)}</td><td>${esc(impact.baselineWeeks)} weeks</td><td>${esc(impact.assistedWeeks)} week</td></tr></tbody></table><p class="win-note">${esc(impact.label)}. ${esc(impact.assumptions)} ${esc(impact.exclusions)}</p>`;
  }
 }
 function clear(query){const result=noSupportedRoute({query,searchedSources:graph.sources.map(s=>s.title),searchedTypes:[...new Set(graph.nodes.map(n=>n.type))],considered:['FRDA–ISCU mechanism comparison','FRDA–A-T phenotype-only candidate (rejected)'],missingEvidence:['No approved action journey for this focal entity.'],nextQuestion:'Which authoritative source connects this disease to a mechanism and an available research asset?'});$('win-result').hidden=true;$('journey-summary').hidden=true;$('win-panel').replaceChildren();$('journey-action').replaceChildren();$('journey-path').replaceChildren();$('win-empty').hidden=false;$('win-empty').innerHTML=`<h2>No supported connection found</h2><p>No recommendation is retained for “${esc(query)}”.</p><p>${esc(result.nextQuestion||'Find a mechanism-specific source and a research asset owner.')}</p><details><summary>What was searched and why candidates failed</summary><p>Types: ${esc([...new Set(graph.nodes.map(n=>n.type))].join(', '))}</p><p>Sources: ${esc(graph.sources.map(s=>s.title).join('; '))}</p><p>The supported demonstration starts with FRDA. ISCU is a mechanism comparison requiring expert review; A-T is rejected as phenotype-only. Other focal diseases lack an asset-to-action path in this snapshot.</p></details>`;$('journey-status').textContent='No supported route. Previous recommendations cleared.';}
 function start(focus=false){const query=$('win-query').value;const match=resolver.resolve(query);if(!validation.valid||match.nodeId!==focalId){clear(query);return;}$('win-empty').hidden=true;$('win-result').hidden=false;$('journey-summary').hidden=false;updateSummary();action();render();$('journey-path').innerHTML='<details><summary>Inspect the graph branches behind this proposal</summary>'+graph.journey.routes.map(route=>{const valid=route.edgeIds.length===route.nodeIds.length-1&&route.edgeIds.every((id,i)=>{const e=edges.get(id);return e&&[e.from,e.to].includes(route.nodeIds[i])&&[e.from,e.to].includes(route.nodeIds[i+1]);});return valid?`<p><b>${esc(route.label)}</b></p>`+route.edgeIds.map((id,i)=>`<button data-evidence="${esc(id)}">${esc(nodes.get(route.nodeIds[i]).canonicalName)} → ${esc(nodes.get(route.nodeIds[i+1]).canonicalName)}</button>`).join(''):'<p>Branch withheld: supporting edge missing.</p>';}).join('')+'</details>';$('journey-status').textContent='Research proposal · expert review pending';if(focus)$('win-panel').focus({preventScroll:true});}
 $('show-opportunity').onclick=()=>{active='connection';start(true);};$('win-search-form').onsubmit=e=>{e.preventDefault();start(true);};$('win-query').oninput=()=>{if(resolver.resolve($('win-query').value).nodeId!==focalId)clear($('win-query').value);else start();};
 document.querySelectorAll('[data-win-step]').forEach(b=>b.onclick=()=>{active=b.dataset.winStep;render();const [number,label]=stepMeta[active];$('journey-status').textContent=`Journey step ${number} of 5: ${label}. Research proposal · expert review pending.`;$('win-panel').focus({preventScroll:true});});
 $('patient-journey').addEventListener('click',e=>{if(e.target.closest('[data-action-evidence]'))showEvidence(opportunity.action.edgeIds);const c=e.target.closest('[data-evidence]');if(c)showEvidence([c.dataset.evidence]);const n=e.target.closest('[data-win-node]');if(n){const node=nodes.get(n.dataset.winNode);dialog(node.canonicalName,`<p>${esc(node.description)}</p><p class="review-label">${esc(node.reviewStatus)}</p>`+evidence(graph.edges.filter(e=>e.from===node.id||e.to===node.id).map(e=>e.id)));}});
 $('inspect-journey-evidence').onclick=()=>showEvidence(graph.edges.map(e=>e.id));
 $('win-ai').onclick=()=>dialog('OpenAI build and extraction trail',`<p><b>OpenAI Codex assisted implementation and build-time structured extraction; no runtime model or paid API call is used.</b></p><p>The structured candidates remain pending independent expert review. The exact model identifier was not exposed by the session, and human approval is not claimed. Removing supporting edges suppresses the corresponding explanation.</p><pre>${esc(JSON.stringify(extractionArtifact,null,2))}</pre>`);
 $('win-close').onclick=()=>inspector.close();inspector.addEventListener('cancel',event=>{event.preventDefault();inspector.close();});inspector.addEventListener('click',event=>{if(event.target===inspector){const rect=inspector.getBoundingClientRect();const outside=event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom;if(outside)inspector.close();}});inspector.addEventListener('close',()=>returnFocus?.focus());start();
}
